<?php
//API that verifies the user when they click on the verification link.


//TODO: SHOULD REDIRECT USER TO PAGE WITH SWEET ALERT SAYING THEY CAN NOW LOG IN.
//WHEN CLICKING ON BUTTON, REDIRECT TO HOME PAGE! - INDEX-VERIFIED.HTML THAT LOOKS LIKE INDEX.HTML 
//BUT POPS UP WITH SWEET ALERT SAYING YOU NOW CAN LOG IN AND WHEN CLICKING ON BUTTON YOU WILL BE REDIRECTED TO INDEX.HTML


?>